### ISSUE TITLE
Volume controll is not working linear

### ISSUE THREAD

**Issue by tomekceszke** [Fornoth/spotify-connect-web#85] opened 2016-09-13 19:38 UTC
Dear Maintainer,
first of all many thanks for that amazing tool!

I noticed that volume level that is passed from Spotify to Alsa thru spotify-connect-web is somehow converted. Unfortunately that conversion is not linear, but exponential (pic rel).
Is there a chance to have 1:1 conversion? I mean 50% in Spotify is equal 50% in alsa(mixer)?

My environment:
Raspberry Pi 2 
OS: OSMC (Debian based)
Spotify-connect-web release 0.0.3

![volume_controll_spotify_web_connect](https://cloud.githubusercontent.com/assets/4999673/18488572/4e5beb2c-79fa-11e6-8b88-a8172e217b2f.PNG)

**Comment by tjerkdekuijper** [comment] 2016-09-15 11:39
I can confirm this issue. I have got the same problem on my Raspberry Pi 3 with OSMC

**Comment by flori4n** [comment] 2016-09-15 21:39
Try to start spotify-connect-web.sh with --dbrange 45
this should help

**Comment by awiouy** [comment] 2016-09-15 21:42
@flori4n is there a systematic way to compute dbrange?

**Comment by flori4n** [comment] 2016-09-15 21:46
@awiouy Sorry not that I know. I'll try different --dbrange and see witch one suit best for me.

**Comment by tomekceszke** [comment] 2016-09-15 21:55
@flori4n many thanks for that hint - now volume control works as I want

edit:
I don't know if I should close this issue, in my opinion it should work in this way by default. Maybe it depends on platform/os?

**Comment by Fornoth** [comment] 2016-10-02 05:48
See #22, this is a hardware issue unfortunately. It's because devices report a larger volume range than they can actually handle

**Comment by Fornoth** [comment] 2016-12-12 06:14
I'm gonna close this for now, feel free to re-open if you're still having problems

**Closed as completed by Fornoth** 2016-12-12 06:14 UTC

**Comment by bartberden** [comment] 2017-01-24 18:06
It seems I'm having this issue as well.. Im using a IQaudio DAC, and my volume doesn't scale properly (below 50% i hear nothing, so my range is 50-100%). As I'm not that technical, what should I do to fix this?
