### ISSUE TITLE
[Raspberry Pi 2] Random Stops in Playback

### ISSUE THREAD

**Issue by smartsoldier** [Fornoth/spotify-connect-web#110] opened 2017-01-19 23:58 UTC
I did a fresh install with PiBakery and after my apt-get updates etc I installed spotify-connect-web. I set it up to run at each boot, and it works beautifully...until it doesn't. It will randomly stop playback for 10-30 seconds, and then continue on like nothing happened (maybe skipping that time in the music it is hard to tell). I am thinking it is either Wifi signal or power supply. Am I missing anything software-wise that I could fix easily? If not, how can I test if it is Wifi / power? Thanks.

**Comment by RafaPolit** [comment] 2017-01-24 13:36
Having the same issue on RPi3. There are also times when this behavior is more of a stutter than a complete stop. I believe as well that it is a wifi issue, as during this time any ssh session gets laggy, connecting new sessions to the RPi may timeout, and web server is also slow to respond.

Haven't thought of power supply issues, but I am using a good iPad charger that are, supposedly, very stable.

There is also not a significant load when this happens, maybe 6% of the CPU and plenty of free memory, so I don't the think it's resources.

Any insight into what it maybe? Thanks,
Rafa.

**Comment by smartsoldier** [comment] 2017-01-26 00:38
Actually I think mine was a power supply issue. I changed outlets and used a different charger and now it works flawlessly.

**Comment by RafaPolit** [comment] 2017-01-28 05:47
That's funny, because I changed from WiFi to wired Ethernet connection and my problems where solved! I'm pretty sure it was a WiFi issue as ssh connections into the RPi where also delayed and copying files took forever.

**Comment by keab** [comment] 2017-02-05 16:22
I've had similar problems with the Spotify client in Volumio (RPi1 hw) . It was caused by the caching of files to SD card not being fast enough. I solved it by caching to a ramdisk instead. A faster SD card might also solve it.  (Strangely enough I don't have the problem after upgrading to Volumio 2)

**Comment by Fornoth** [comment] 2018-01-15 17:38
I'm gonna close this for now, feel free to re-open if you're still having problems

**Closed as completed by Fornoth** 2018-01-15 17:39 UTC
